clear all
close all
clc

text_size = 20;
eigenmode_nogrid = figure('Position', get(0, 'Screensize'));
out = imtile( ...
  {'images\thk_0_mode1_nogrid.png', 'images\thk_0_mode4_nogrid.png', ...
  'images\thk_5_mode1_nogrid.png', 'images\thk_5_mode4_nogrid.png', ...
  'images\thk_100_mode1_nogrid.png', 'images\thk_100_mode4_nogrid.png'}, ...
  'GridSize', [3, 2], ...
  'BackgroundColor', 'w');
imshow(out)
saveas(eigenmode_nogrid, ['C:\Users\Niccolò\Documents\UNIVERSITA\5° ANNO\FEM\' ...
  'assignment2\ex4\images\eigenmode_nogrid.png'],'png');

figure()
eigenmode_grid = figure('Position', get(0, 'Screensize'));
out2 = imtile( ...
  {'images\thk_0_mode1_grid.png', 'images\thk_0_mode4_grid.png', ...
  'images\thk_5_mode1_grid.png', 'images\thk_5_mode4_grid.png', ...
  'images\thk_100_mode1_grid.png', 'images\thk_100_mode4_grid.png'}, ...
  'GridSize', [3, 2], ...
  'BackgroundColor', 'w');
imshow(out2)
saveas(eigenmode_grid, ['C:\Users\Niccolò\Documents\UNIVERSITA\5° ANNO\FEM\' ...
  'assignment2\ex4\images\eigenmode_grid.png'],'png');